# Permalinks
#
#permalink:           pretty
permalink: /musings/:year/:month/:day/:title.html

# Setup
title:               Musings
tagline:             ''
description:         'Description'
url:                 http://jason.deabill.com
baseurl:             '/musings'
paginate:            5
paginate_path:       '/musings/page:num'

# About/contact
author:
  name:              Jason Deabill
  url:               https://twitter.com/incongruousm
  email:             

# Custom vars
#version:             1.0.0
highlighter:         rouge

kramdown:
  input:             GFM
